---
- name: configure | create consul daemon folder
  ansible.builtin.file:
    path: /etc/consul.d
    state: directory
    mode: '0700'
  become: true

- name: configure | add consul user
  ansible.builtin.user:
    name: consul
    shell: /bin/false
    home: /etc/consul.d
    system: yes

- name: install | create consul data dir
  ansible.builtin.file:
    path: /opt/consul
    group: consul
    owner: consul
    state: directory
    mode: '0755'
  become: true

# TODO: prepare security credentials

# TODO: configure consul agents
- name: configure | create consul agent config
  ansible.builtin.template:
    src: etc/consul.d/consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    group: consul
    owner: consul
    mode: '640'
  become: true

# TODO: configure consul servers