---
# tasks file for ansible-consul
- name: install prerequisites
  ansible.builtin.package:
    name: "{{ PACKAGES }}"
    state: present
  become: true

- name: install consul
  include_tasks: tasks/install.yaml

- name: configure consul
  include_tasks: tasks/configure.yaml
